<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controls\BrushSetup\RadialBrushSetup\RadialBrushSetupView.xaml~RFc7f64e.TMP" />
    <None Remove="Plugins\Elements\Gold\yellow-1845394.jpg" />
    <None Remove="stylecop.json" />
    <None Remove="ViewModels\ElementViewModel.cs~RF2ba99c.TMP" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EBoardConfigManager\EBoardConfigManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Plugins\Elements\BasicAV\BasicAVMainView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\StandardText\StandardTextView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Shapes\Ellipse\EllipseView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Shapes\Rectangle\RectangleView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\EmptyLinear\EmptyLinearView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\EmptyRadial\EmptyRadialView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Tools\Summoner\SummonerView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Tools\UptimeTimer\UptimeTimerView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\EBoardBrowserView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\EBoardView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ElementView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MainWindowLogoutBar.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MainWindowMenuBar.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SplashScreen.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Plugins\Addons\Snake\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Plugins\Elements\Gold\yellow-1845394.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Plugins\Elements\Gold\gold-textur-tapete.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Plugins\Elements\Gold\metallischer-goldhintergrund.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
