<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EBoardConfigManager\EBoardConfigManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\FluidUIDataBlock\FluidUIDataBlockSetupMenuItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FluidUIDesign\FluidUIDesignSetupMenuItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FluidUIFont\FluidUIFontSetupMenuItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FluidUISize\FluidUISizeSetupMenuItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FluidUIStand\FluidUIStandSetupMenuItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\BasicAV\BasicAVMainView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\StandardText\StandardTextView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Shapes\Ellipse\EllipseView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Shapes\Rectangle\RectangleView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\EmptyLinear\EmptyLinearView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Elements\EmptyRadial\EmptyRadialView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Eboard\Summoner\SummonerView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Tools\UptimeTimer\UptimeTimerView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\NavigationContextView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\EBoardView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ElementView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Eboard\LogOutBar\LogOutBarView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\Eboard\MenuBar\MenuBarView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\SplashScreen.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Plugins\Addons\Snake\" />
    <Folder Include="Plugins\System\" />
  </ItemGroup>

</Project>
